### PR TITLE
Update controller.py

### PR DESCRIPTION
**Pull request by abhra2020-smart**
Movement (and mining system)

[IMPORTANT] Do not merge yet. It is incomplete. We need gravity.
This is still spectator mode.

### CODE REVIEW

**Comment by abhra2020-smart** [comment]
Title screen? esc menu? Yeah, adding that too.

**Comment by obiwac** [comment]
Awesome! :smile: 

Quick tip: you can work on your own changes before submitting a PR by creating a feature branch on your fork of this repository ([`abhra2020-smart/python-minecraft-clone`](https://github.com/abhra2020-smart/python-minecraft-clone) in your case).

**Comment by abhra2020-smart** [comment]
wtf response so quick damn

**Comment by abhra2020-smart** [comment]
Also, I'll convert it to draft. I was just too lazy to fork and PR.

**Comment by obiwac** [comment]
> wtf response so quick damn

Night and day I dwell on GitHub.

> Also, I'll convert it to draft. I was just too lazy to fork and PR.

Well in any case that's exactly what GitHub does; create a fork and a branch (`patch-5`).

**Comment by abhra2020-smart** [comment]
Normal 9 y.o: plays Minecraft
Me (a 9 y.o): clones Minecraft

Big diff

**Pull request closed without merging**
