### PR TITLE
Update cactus.py

### PR DESCRIPTION
**Pull request by abhra2020-smart**
It is a bit buggy (probably) but we'll have to test it, right?

### CODE REVIEW

**Comment by obiwac** [comment]
Could you elaborate on how it's buggy (with screenshots, for example)?

**Comment by abhra2020-smart** [comment]
Uhhh... I'm currently getting an error:
Traceback (most recent call last):
  File "C:\Users\abhra\PycharmProjects\CodeLegend\Minecraft\main.py", line 9, in <module>
    import pyglet.gl as gl
  File "C:\Users\abhra\PycharmProjects\CodeLegend\venv\lib\site-packages\pyglet\gl\__init__.py", line 95, in <module>
    from pyglet.gl.lib import GLException
  File "C:\Users\abhra\PycharmProjects\CodeLegend\venv\lib\site-packages\pyglet\gl\lib.py", line 36, in <module>
    import ctypes
  File "C:\Users\abhra\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 474, in <module>
    GetLastError = windll.kernel32.GetLastError
  File "C:\Users\abhra\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 390, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\abhra\AppData\Local\Programs\Python\Python38-32\lib\ctypes\__init__.py", line 395, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self._handle))
AttributeError: 'int' object has no attribute '_handle'

**Comment by abhra2020-smart** [comment]
I'll clone the project and see...

**Comment by abhra2020-smart** [comment]
But rn I'm busy with school

**Comment by abhra2020-smart** [comment]
It's break now, and I actually can't show you the cactus' because of an error.
Here's a screenshot of the error:
image

**Comment by abhra2020-smart** [comment]
I'll close this pull request.

**Comment by obiwac** [comment]
> It's break now, and I actually can't show you the cactus' because of an error.
> Here's a screenshot of the error:
> image
> 

How are you declaring the "vertex_positions" variable?

**Comment by abhra2020-smart** [comment]
i git-cloned it ;)

**Pull request closed without merging**
